#include "html_report.h"
#include "../core/config.h"
#include "../core/fsutil.h"
#include <fstream>

namespace reports {

void write_html(const scanner::ScanResult& r) {
    std::string file =
        config::REPORT_HTML_DIR + "/scan_" + fsutil::timestamp() + ".html";

    std::ofstream out(file);
    out << "<!DOCTYPE html><html><head><meta charset='UTF-8'>"
        << "<title>Sentinel-C Report</title>"
        << "<style>"
        << "body{background:#0b0f14;color:#e6edf3;font-family:monospace}"
        << "table{border-collapse:collapse;width:100%}"
        << "th,td{border:1px solid #30363d;padding:8px}"
        << "th{background:#161b22}"
        << ".new{color:#3fb950}.mod{color:#d29922}.del{color:#f85149}"
        << "</style></head><body>";

    out << "<h1>Sentinel-C v3.50 Scan Report</h1>";

    out << "<table><tr><th>Status</th><th>File</th></tr>";
    for (auto& [p,_]: r.added)    out << "<tr class='new'><td>NEW</td><td>"<<p<<"</td></tr>";
    for (auto& [p,_]: r.modified) out << "<tr class='mod'><td>MODIFIED</td><td>"<<p<<"</td></tr>";
    for (auto& [p,_]: r.deleted)  out << "<tr class='del'><td>DELETED</td><td>"<<p<<"</td></tr>";
    out << "</table>";

    out << "<footer><hr>Generated by Sentinel-C v3.50</footer>";
    out << "</body></html>";
}

}
