#include "database.h"
#include <filesystem>
#include <fstream>
#include <iomanip>

namespace fs = std::filesystem;

static const std::string BASE = "sentinel-c-logs/";
static const std::string DATA = BASE + "data/";
static const std::string LOGS = BASE + "logs/";
static const std::string REP  = BASE + "reports/";

namespace database {

void init_storage() {
    fs::create_directories(DATA);
    fs::create_directories(LOGS);
    fs::create_directories(REP + "cli");
    fs::create_directories(REP + "html");
    fs::create_directories(REP + "json");
}

void save_baseline(const std::vector<common::FileEntry>& files) {
    std::ofstream out(DATA + ".sentinel-baseline");
    for (auto& f : files)
        out << f.path << "|" << f.size << "|" << f.hash << "\n";
}

std::unordered_map<std::string, common::FileEntry> load_baseline() {
    std::unordered_map<std::string, common::FileEntry> map;
    std::ifstream in(DATA + ".sentinel-baseline");
    std::string line;

    while (std::getline(in, line)) {
        auto p1 = line.find('|');
        auto p2 = line.find('|', p1 + 1);

        common::FileEntry f;
        f.path = line.substr(0, p1);
        f.size = std::stoull(line.substr(p1 + 1, p2 - p1 - 1));
        f.hash = line.substr(p2 + 1);
        map[f.path] = f;
    }
    return map;
}

void log_action(const std::string& action, const std::string& path) {
    std::ofstream log(LOGS + "scan.log", std::ios::app);
    log << common::now_string() << " " << action << " " << path << "\n";
}

void generate_reports(
    const std::vector<common::FileEntry>& A,
    const std::vector<common::FileEntry>& M,
    const std::vector<common::FileEntry>& D,
    const std::string& root
) {
    std::string ts = common::now_string();
    std::replace(ts.begin(), ts.end(), ' ', '_');
    std::replace(ts.begin(), ts.end(), ':', '-');

    /* ---------- CLI TXT ---------- */
    {
        std::ofstream out(REP + "cli/scan_" + ts + ".txt");
        out << "Sentinel-C v4.0\nScan Path: " << root << "\n\n";
        for (auto& f : A) out << "[NEW] " << f.path << "\n";
        for (auto& f : M) out << "[MOD] " << f.path << "\n";
        for (auto& f : D) out << "[DEL] " << f.path << "\n";
    }

    /* ---------- HTML ---------- */
    {
        std::ofstream h(REP + "html/scan_" + ts + ".html");
        h << "<html><body style='background:#111;color:#eee;font-family:monospace'>";
        h << "<h2>Sentinel-C v4.0</h2><table border='1'>";
        for (auto& f : A) h << "<tr style='color:lime'><td>NEW</td><td>" << f.path << "</td></tr>";
        for (auto& f : M) h << "<tr style='color:yellow'><td>MOD</td><td>" << f.path << "</td></tr>";
        for (auto& f : D) h << "<tr style='color:red'><td>DEL</td><td>" << f.path << "</td></tr>";
        h << "</table><footer>Generated by Sentinel-C v4.0</footer></body></html>";
    }

    /* ---------- JSON ---------- */
    {
        std::ofstream j(REP + "json/scan_" + ts + ".json");
        j << "{\n\"version\":\"4.0\",\n\"root\":\"" << root << "\",\n";
        j << "\"new\":" << A.size() << ",\"modified\":" << M.size()
          << ",\"deleted\":" << D.size() << "\n}";
    }
}

}
